name: OpenOSRS - Pull Request

on: pull_request

jobs:
  assignAuthor:
    name: Assign author
    runs-on: ubuntu-latest

    steps:
      - name: Assign author to PR
        if: github.event.action == 'opened'
        uses: technote-space/assign-author@v1
        with:
          GITHUB_TOKEN: ${{ secrets.OpenOSRS }}

  pr-lint:
    name: Title linter
    runs-on: ubuntu-latest

    steps:
      - name: Linting PR titile
        if: github.event_name == 'pull_request'
        uses: seferov/pr-lint-action@master
        with:
          title-regex: '^\w+: \w+'

  triage:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Labeler
        continue-on-error: true
        uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.OpenOSRS }}"